AWSTemplateFormatVersion: 2010-09-09
Description: "EC2 Image Builder Stack - test"

Parameters:
  BaseImageArn:
    Type: String
    Description: "The base AMI ARN to be used for your Image Recipe to build upon."
    Default: "arn:aws:imagebuilder:ap-southeast-2:aws:image/amzn2-ami-hvm-2.0.20211001.1-x86_64-gp2/x.x.x"
  ServerScriptUri:
    Type: String
    Description: "The URI of the CIS level one scripts for the custom component"
    Default: "image-builder-scripts-903rg93g"
  Description:
    Type: String
    Description: "A general description of your image resources"
    Default: "Hardened amazon linux image"
  ImageName:
    Type: String
    Description: "Desired name of your image resources"
    Default: "amazon-linux-2-=-hardened"
  Version:
    Type: String
    Description: "The semantic version of the deployment. You must increment this value for every CloudFormation change"

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            ExpirationInDays: 7

  Topic:
    Type: AWS::SNS::Topic

  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: ImageBuilderPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "ssm:SendCommand"
                  - "ec2:CreateTags"
                  - "ec2:AttachVolume"
                  - "ec2:CreateTags"
                  - "ec2:CreateVolume"
                  - "ec2:DeleteVolume"
                  - "ec2:DescribeVolumes"
                  - "ec2:DetachVolume"
                Resource: "*"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/EC2InstanceProfileForImageBuilder"
        - "arn:aws:iam::aws:policy/AWSImageBuilderFullAccess"
        - "arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM"
        - "arn:aws:iam::aws:policy/service-role/AmazonSSMAutomationRole"
        - "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - !Ref Role

  ImageArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${AWS::StackName}/image-arn"
      Type: String
      Value: !Sub "arn:aws:imagebuilder:${AWS::Region}:${AWS::AccountId}:image/${ImageName}/x.x.x"

  Pipeline:
    Type: AWS::ImageBuilder::ImagePipeline
    Properties:
      Description: !Sub "${Description}"
      ImageRecipeArn: !Ref Recipe
      InfrastructureConfigurationArn: !Ref InfrastructureConfiguration
      Name: !Ref ImageName
      DistributionConfigurationArn: !Ref DistributionConfiguration
      Schedule:
        PipelineExecutionStartCondition: EXPRESSION_MATCH_AND_DEPENDENCY_UPDATES_AVAILABLE
        ScheduleExpression: "cron(0 0 12 1/1 * ? *)" # 12:00PM UTC / 22:00PM AEST Daily

  InfrastructureConfiguration:
    Type: AWS::ImageBuilder::InfrastructureConfiguration
    Properties:
      Description: !Ref Description
      TerminateInstanceOnFailure: false
      InstanceProfileName: !Ref InstanceProfile
      Name: !Ref ImageName
      Logging:
        S3Logs:
          S3BucketName: !Ref Bucket
          S3KeyPrefix: !Sub "${ImageName}/Logs"
      SnsTopicArn: !Ref Topic

  DistributionConfiguration:
    Type: AWS::ImageBuilder::DistributionConfiguration
    Properties:
      Name: !Ref ImageName
      Description: !Ref Description
      Distributions:
        - Region: ap-southeast-2
          AmiDistributionConfiguration:
            Name: !Sub "${ImageName}-{{imagebuilder:buildDate}}"
            Description: !Ref Description
            AmiTags:
              Name: !Ref ImageName
            LaunchPermissionConfiguration:
              UserIds: [!Sub "${AWS::AccountId}"]

  Recipe:
    Type: "AWS::ImageBuilder::ImageRecipe"
    Properties:
      Name: !Ref ImageName
      Version: !Ref Version
      ParentImage: !Ref BaseImageArn
      Description: !Ref Description
      Components:
        - ComponentArn: "arn:aws:imagebuilder:ap-southeast-2:aws:component/update-linux/x.x.x"
        - ComponentArn: !Ref ServerComponent
      Tags:
        Name: !Ref ImageName

  ServerComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      name: HelloWorldTestingDocument
      description: This is hello world testing document.
      schemaVersion: 1.0
      
      phases:
        - name: build
          steps:
            -
              name: SampleS3Download
              action: S3Download
              timeoutSeconds: 60
              onFailure: Abort
              maxAttempts: 3
              inputs:
                -
                  source: 's3://image-builder-scripts-903rg93g/script.sh'
                  destination: '/tmp/myapplication/'
            -
              name: HelloWorldStep
              action: ExecuteBash
              inputs:
                commands:
                  - './tmp/myapplication/'



